version: '3'

vars:
  G_COMPONENTS_DIR: "{{.ROOT_DIR}}/components_new"

tasks:
  install-submodules:
    cmds:
      - "git submodule update --init --recursive"

  install-python-libs:
    cmds:
      - "pip install -r requirements.txt"

  start:
    cmds:
      - task: install-submodules
      - task: install-python-libs
      - python3 {{.ROOT_DIR}}/scripts/start_components.py

  stop:
    cmds:
      - python3 {{.ROOT_DIR}}/scripts/stop_components.py

  clean-containers:
    cmds:
      - task: stop
      - python3 {{.ROOT_DIR}}/scripts/clean_containers.py

  clean-images:
    cmds:
      - task: stop
      - python3 {{.ROOT_DIR}}/scripts/clean_containers.py
      - python3 {{.ROOT_DIR}}/scripts/clean_images.py

  clean-and-restart:
    cmds:
      - task: clean-images
      - cmd: "sudo rm -rf data"
      - task: start
