version: '3'

vars:
  G_COMPONENTS_DIR: "{{.ROOT_DIR}}/components_new"

tasks:
  install-submodules:
    cmds:
      - "git submodule update --init --recursive"

  start:
    dir: "{{.ROOT_DIR}}/scripts/"
    cmds:
      - task: install-submodules
      - python3 start_components.py

  stop:
    dir: "{{.ROOT_DIR}}/scripts/"
    cmds:
      - python3 stop_components.py

  clean-containers:
    dir: "{{.ROOT_DIR}}/scripts/"
    cmds:
      - python3 clean_containers.py

  clean-images:
    dir: "{{.ROOT_DIR}}/scripts/"
    cmds:
      - python3 clean_images.py
